postgres:
  image: postgres:alpine
  hostname: postgres
  ports:
    - 5432:5432
  environment:
    - POSTGRES_DB=rps
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=abc123

redis:
  image: redis:alpine
  hostname: redis
  ports:
    - 6379:6379
